TeamOwori/Owori-Server

build.gradle
src/docs/family.adoc
src/docs/index.adoc
src/main/java/com/owori/config/security/SecurityConfig.java
src/main/java/com/owori/domain/family/controller/FamilyController.java
src/main/java/com/owori/domain/family/dto/request/AddMemberRequest.java
src/main/java/com/owori/domain/family/dto/request/FamilyRequest.java
src/main/java/com/owori/domain/family/dto/response/InviteCodeResponse.java
src/main/java/com/owori/domain/family/entity/Family.java
src/main/java/com/owori/domain/family/repository/FamilyRepository.java
src/main/java/com/owori/domain/family/repository/JpaFamilyRepository.java
src/main/java/com/owori/domain/family/service/FamilyService.java
src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
src/test/java/com/owori/domain/member/controller/AuthControllerTest.java
src/test/java/com/owori/support/docs/RestDocsTest.java

1. 가족 생성 API의 테스트 코드를 통한 API Docs
2. 가족에 멤버 추가 API의 테스트 코드를 통한 API Docs
[API Docs](https://teamowori.github.io/Owori-Api-Docs/)
<br>

[CHORE] 가족 생성 API와 member 가족에 추가 API에 대한 API docs

---

src/main/java/com/owori/domain/family/controller/FamilyController.java
src/main/java/com/owori/domain/member/controller/MemberController.java
src/main/java/com/owori/domain/member/dto/request/MemberDetailsRequest.java
src/main/java/com/owori/domain/member/dto/request/MemberRequest.java

- @Valid 어노테이션 및 dto의 validation 옵션 추가
<br>

[CHORE] member와 family request dto에 validation 추가

---

build.gradle
src/main/java/com/owori/config/security/jwt/JwtTokenProvider.java
src/main/java/com/owori/domain/member/client/KakaoMemberClient.java
src/main/java/com/owori/domain/member/controller/advice/MemberErrorAdvice.java
src/main/java/com/owori/domain/member/dto/client/KakaoMemberResponse.java
src/main/java/com/owori/domain/member/entity/OAuth2Info.java
src/main/java/com/owori/domain/member/exception/WebClientException.java
src/main/java/com/owori/domain/member/mapper/MemberMapper.java
src/main/java/com/owori/domain/member/repository/JpaMemberRepository.java
src/main/java/com/owori/domain/member/repository/MemberRepository.java
src/main/java/com/owori/domain/member/service/AuthService.java
src/main/java/com/owori/domain/member/service/MemberService.java

- webclient 을 통한 카카오 요청 및 가져온 client id로 검증하도록 수정
<br>

[FEAT] webclient 로그인 api 적용

---

src/docs/family.adoc
src/main/java/com/owori/domain/family/controller/FamilyController.java
src/main/java/com/owori/domain/family/entity/Family.java
src/main/java/com/owori/domain/family/service/FamilyService.java
src/main/java/com/owori/domain/member/controller/MemberController.java
src/main/java/com/owori/domain/member/service/MemberService.java
src/main/java/com/owori/global/dto/ImageResponse.java
src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
src/test/java/com/owori/domain/member/controller/MemberControllerTest.java

- 가족 사진 저장 api
- api docs
<br>

[FEAT] 가족 사진 저장 api 및 api docs

---

src/main/java/com/owori/domain/member/service/MemberService.java

[FEAT] apple login api 처리

---

src/docs/story.adoc
src/main/java/com/owori/domain/story/controller/StoryController.java
src/main/java/com/owori/domain/story/mapper/StoryMapper.java
src/main/java/com/owori/domain/story/repository/StoryRepositoryCustom.java
src/main/java/com/owori/domain/story/repository/StoryRepositoryCustomImpl.java
src/main/java/com/owori/domain/story/service/StoryService.java
src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
src/test/java/com/owori/domain/story/service/StoryServiceTest.java

Closes #52 
- 유저가 좋아한 이야기 API 구현
- 유저가 작성한 이야기 API 구현
<br>

[FEAT] 유저가 좋아한 이야기 / 작성한 이야기 API, API Docs

---

src/main/java/com/owori/domain/member/dto/request/MemberDetailsRequest.java
src/main/java/com/owori/domain/member/service/MemberService.java

[CHORE] rename dto variable

---

docker-compose.yml
nginx/Dockerfile
nginx/nginx.conf

- nginx 설정 파일 작성
- docker 설정 추가
- 머지되면 도커로 실행시 포트 번호(8080) 생략 후 api 요청을 보내야 함
<br>

[FEAT] NginX 추가

---

src/main/java/com/owori/domain/comment/service/CommentService.java
src/main/java/com/owori/domain/heart/service/HeartService.java
src/main/java/com/owori/domain/image/service/ImageService.java
src/main/java/com/owori/domain/keyword/service/KeywordService.java
src/main/java/com/owori/domain/story/service/FacadeService.java
src/main/java/com/owori/domain/story/service/StoryService.java

Closes #70 
@Transactional을 빼먹어 발생한 오류였습니다. 앞으로 더 꼼꼼하게 확인해보겠습니다 ......
<br>

[FIX] 좋아요 재생성 오류 해결 

---

.github/workflows/owori-cd.yml
build.gradle
docker-compose.prod.yml
src/main/java/com/owori/domain/member/service/MemberService.java
src/main/resources/application-prod.yml

- application-prod.yml 파일 작성
- docker-compose.prod.yml 파일 작성
- github actions의 cd를 위한 yml파일 작성
- 기타 오류 수정
- github actions 작성 하긴 했는데 정상 작동하는지 확인 필요
<br>

[CHORE] 배포 세팅

---

src/main/java/com/owori/domain/comment/service/CommentService.java
src/main/java/com/owori/domain/keyword/service/KeywordService.java
src/main/java/com/owori/domain/story/controller/StoryController.java
src/main/java/com/owori/domain/story/dto/request/PostStoryRequest.java
src/main/java/com/owori/domain/story/exception/InvalidUserException.java
src/main/java/com/owori/domain/story/service/StoryService.java
src/main/java/com/owori/global/advice/GlobalErrorAdvice.java

Closes #67 
- dto validation 적용했습니다.
- 수정, 삭제 시 유저를 검증하는 코드를 추가했습니다.
<br>

[REFACTOR] story 관련 validation 추가 

---

src/main/java/com/owori/config/security/SecurityConfig.java
src/main/java/com/owori/domain/test/TestController.java
src/main/java/com/owori/domain/test/TestService.java

Closes #78 
- api 연동의 편의를 위해 제작했습니다. 추후 삭제할 예정입니다.
<br>

[TEST] 더미데이터 추가 API

---

src/main/java/com/owori/global/audit/AuditListener.java

Closes #80 
basetime 설정을 수정했습니다. 
해결했습니다
<br>

[FIX] basetime 설정 수정

---

src/docs/member.adoc
src/main/java/com/owori/domain/member/controller/MemberController.java
src/main/java/com/owori/domain/member/dto/response/MemberColorResponse.java
src/main/java/com/owori/domain/member/entity/Color.java
src/main/java/com/owori/domain/member/mapper/MemberMapper.java
src/main/java/com/owori/domain/member/service/MemberService.java
src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
src/test/java/com/owori/domain/member/service/MemberServiceTest.java

[FEAT] 멤버의 수정 가능 색상 조회 api, api docs

---

src/docs/family.adoc
src/docs/member.adoc
src/main/java/com/owori/aspect/LogIntroduction.java
src/main/java/com/owori/aspect/Logger.java
src/main/java/com/owori/domain/family/controller/FamilyController.java
src/main/java/com/owori/domain/family/controller/advice/FamilyErrorAdvice.java
src/main/java/com/owori/domain/family/entity/Family.java
src/main/java/com/owori/domain/family/exception/InviteCodeExistException.java
src/main/java/com/owori/domain/family/service/FamilyService.java
src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
src/test/java/com/owori/domain/family/service/FamilyServiceTest.java

- 가족 초대 코드 재생성 api, api docs
<br>

[FEAT] 가족 초대 코드 재생성 api, api docs

---

src/main/java/com/owori/domain/saying/controller/SayingController.java
src/main/java/com/owori/domain/saying/dto/request/AddSayingRequest.java
src/main/java/com/owori/domain/saying/dto/request/UpdateSayingRequest.java
src/main/java/com/owori/domain/schedule/controller/ScheduleController.java
src/main/java/com/owori/domain/schedule/dto/request/AddScheduleRequest.java
src/main/java/com/owori/domain/schedule/dto/request/UpdateScheduleRequest.java
src/main/java/com/owori/domain/schedule/dto/response/ScheduleDDayResponse.java
src/main/java/com/owori/domain/schedule/mapper/ScheduleMapper.java
src/main/resources/application-local.yml

일정 API validation 추가 및 null 처리
서로에게 한마디 API validation 추가 및 null 처리

[REFACTOR] 일정, 서로에게 한마디 관련 validation 추가 및 null 예외처리

---

src/main/java/com/owori/domain/keyword/service/KeywordService.java
src/main/java/com/owori/domain/story/entity/Story.java
src/main/java/com/owori/domain/story/service/StoryService.java
src/test/java/com/owori/domain/heart/service/HeartServiceTest.java
src/test/java/com/owori/domain/story/service/StoryServiceTest.java

Closes #91 
- 리팩토링 이후 테스트 코드에서 오류가 발생해 수정했습니다. (Story / Heart)
- Story에서 사용하지 않는 함수 제거했습니다.
- 권한 관련 오류가 발생해 해결했습니다. 
<br>

[FIX] 테스트 코드, 예외처리 수정

---

src/main/java/com/owori/domain/family/controller/FamilyController.java
src/main/java/com/owori/domain/family/dto/response/FamilyImageResponse.java
src/main/java/com/owori/domain/family/service/FamilyService.java
src/main/java/com/owori/domain/image/controller/ImageController.java
src/main/java/com/owori/domain/image/dto/response/ImagesStoryResponse.java
src/main/java/com/owori/domain/image/entity/Image.java
src/main/java/com/owori/domain/image/repository/ImageRepository.java
src/main/java/com/owori/domain/image/repository/JpaImageRepository.java
src/main/java/com/owori/domain/image/service/ImageService.java
src/main/java/com/owori/domain/member/controller/MemberController.java
src/main/java/com/owori/domain/member/dto/response/MemberImageResponse.java
src/main/java/com/owori/domain/member/service/MemberService.java
src/main/java/com/owori/domain/story/dto/request/PostStoryRequest.java
src/main/java/com/owori/domain/story/dto/request/UpdateStoryRequest.java
src/main/java/com/owori/domain/story/dto/response/FindAllStoryResponse.java
src/main/java/com/owori/domain/story/dto/response/FindStoryResponse.java
src/main/java/com/owori/domain/story/mapper/StoryMapper.java
src/main/java/com/owori/domain/story/service/StoryService.java
src/test/java/com/owori/domain/family/controller/FamilyControllerTest.java
src/test/java/com/owori/domain/image/controller/ImageControllerTest.java
src/test/java/com/owori/domain/member/controller/MemberControllerTest.java
src/test/java/com/owori/domain/story/controller/StoryControllerTest.java
src/test/java/com/owori/domain/story/service/StoryServiceTest.java

- 이야기 조회 API에서 변수명 변경 : image -> thumbnail
- 이야기 상세 조회 API에서 response에 필드 추가 : start_date, end_date
<br>

[REFACTOR] story DTO field명 변경 및 추가

---

docker-compose.prod.yml
src/main/resources/application-prod.yml

이슈 번호 #102 
데이터베이스를 도커에서 rds로 변경합니다.

[CHORE] 데이터베이스 변경

---

src/docs/member.adoc
src/main/java/com/owori/config/security/SecurityConfig.java
src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
src/main/java/com/owori/domain/member/controller/MemberController.java
src/main/java/com/owori/domain/member/dto/client/GoogleMemberResponse.java
src/main/java/com/owori/domain/member/dto/request/MemberGoogleRequest.java
src/main/java/com/owori/domain/member/entity/AuthProvider.java
src/main/java/com/owori/domain/member/service/MemberService.java
src/test/java/com/owori/domain/member/controller/MemberControllerTest.java

- Google 로그인 api docs 작성
- Google 로그인 API 구현
- 소셜 로그인 api docs 수정
<br>

[FEAT] Google 로그인 API 구현

---

src/docs/comment.adoc
src/docs/heart.adoc
src/docs/image.adoc
src/docs/keyword.adoc
src/docs/story.adoc
src/test/java/com/owori/domain/comment/controller/CommentControllerTest.java
src/test/java/com/owori/domain/heart/controller/HeartControllerTest.java
src/test/java/com/owori/domain/image/controller/ImageControllerTest.java
src/test/java/com/owori/domain/keyword/controller/KeywordControllerTest.java
src/test/java/com/owori/domain/story/controller/StoryControllerTest.java

[DOCS] story, keyword, image, heart, comment API 명세서 업데이트

---

build.gradle
src/main/java/com/owori/config/security/SecurityConfig.java
src/main/resources/application-prod.yml

closes #114 
- actuator와 prometheus의 의존성을 추가하였습니다. 
- actuator는 admin만 접근 가능하도록 설정했습니다.
<br>

[CHORE] 서버 모니터링 시스템 구축

---

build.gradle
src/main/java/com/owori/domain/member/client/GoogleMemberClient.java
src/main/java/com/owori/domain/member/exception/InvalidTokenException.java

1. 구글 로그인 reqeust 필드값 변경( accessToken -> idToken)
2. idToken 무결성 확인 후 복호화
3. DB에서 사용자 유무 판단 후 계정 생성 또는 로그인 수행
<br>

[FIX] Google 로그인 로직 수정

---

src/main/java/com/owori/config/security/SecurityConfig.java

[FIX] actuator 접근 role 수정

---

.github/workflows/owori-cd.yml
src/main/java/com/owori/domain/member/entity/Member.java
src/main/java/com/owori/domain/member/entity/Role.java

[FIX] member role 변수명 수정
